# Generated by Django 3.2.16 on 2022-12-15 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pub_date'], 'verbose_name': 'Опросы', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name'], 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Только кириллица', regex='^[А-Яа-я -]*$')], verbose_name='Имя'),
        ),
    ]
